name: deploy

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  deploy-dev:
    # if: github.ref_name == 'develop'
    runs-on: self-hosted-dev
    environment: Development
    steps:
      - uses: actions/checkout@v4

      - name: setup .env file
        run: |
          [System.IO.File]::WriteAllText(".env", "${{ secrets.ENV }}")

      - name: run docker compose
        run: |
          echo "正在往 ${{ github.ref_name }} 伺服器部署..."
          docker compose up -d --build

  deploy-prod:
    if: github.ref_name == 'main'
    runs-on: self-hosted-prod
    environment: Production
    steps:
      - uses: actions/checkout@v4

      - name: setup .env file

        run: |
          echo "${{ secrets.ENV }}" > .env

      - name: run docker compose
        run: |
          echo "正在往 ${{ github.ref_name }} 伺服器部署..."
          docker compose up -d --build
