name: deploy

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - develop

jobs:
  quality:
    uses: ./.github/workflows/quality.yml
    secrets: inherit
    permissions:
      contents: write

  tests:
    uses: ./.github/workflows/tests.yml
    secrets: inherit

  deploy-dev:
    needs: [quality, tests]
    runs-on: self-hosted-dev
    steps:
      - uses: actions/checkout@v4

      - name: setup .env file
        run: |
          echo "${{ secrets.DEV_ENV }}" > .env

      - name: run docker compose
        run: |
          echo "正在往 ${{ github.ref_name }} 伺服器部署..."
          docker compose up -d --build

  deploy-prod:
    needs: [quality, tests]
    if: github.ref_name == 'main'
    runs-on: self-hosted-prod
    steps:
      - uses: actions/checkout@v4

      - name: setup .env file
        run: |
          echo "${{ secrets.PROD_ENV }}" > .env

      - name: run docker compose
        run: |
          echo "正在往 ${{ github.ref_name }} 伺服器部署..."
          docker compose up -d --build
